const tintColor = '#2f95dc';

export default {
	backgroundTint: '#ffffff',
	lightGrey: '#D5E5F2',
	darkBlue: '#011826',
	lightBlue: '#7AACBF',
	lightPink: '#D99CC4',
	coralPink: '#A64B63',
	flat_green: '#2ecc71',
	flat_red: '#e74c3c',
	flat_orange: '#e67e22',
	flat_blue: '#3498db',
	flat_turquoise: '#1abc9c',
	flat_purple: '#9b59b6',
	flat_anthracite: '#34495e',
	perfect_purple: '#191b33',
	mint_blue: '#00f5faa5',

	tintColor,
	tabIconDefault: '#ccc',
	tabIconSelected: tintColor,
	tabBar: '#fefefe',
	errorBackground: 'red',
	errorText: '#fff',
	warningBackground: '#EAEB5E',
	warningText: '#666804',
	noticeBackground: tintColor,
	noticeText: '#fff',
};
